name = "cactus-push"
main = "src/index.js"
compatibility_date = "2026-07-21"

[vars]
FIREBASE_PROJECT_ID = "couple-game-9f881"
FIREBASE_DATABASE_URL = "https://couple-game-9f881-default-rtdb.europe-west1.firebasedatabase.app"
FIREBASE_WEB_API_KEY = "AIzaSyBsieGW6fu5RmTrmrrumIoSOm600HSn160"

[triggers]
crons = ["*/5 * * * *"]
